twig:
    file_name_pattern: '*.twig'
    form_themes: [ 'bootstrap_5_horizontal_layout.html.twig' ]

    globals:
        cartHandler: '@App\Service\CartHandler'


when@test:
    twig:
        strict_variables: true
